package GUI;

import BD.GestionUsuarioBD;
import entidades.Usuario;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    GestionUsuarioBD conexionUsuario;
    Usuario usuario;
    boolean escribeEnUsuario = true;
    String cadenaUser;
    String cadenaPass;

    /**
     * Creates new form Login
     */
    public Login() {
        conexionUsuario = new GestionUsuarioBD("localhost", "root", "", "tpv", 3306);
        usuario = new Usuario();
        cadenaUser = "";
        cadenaPass = "";
        initComponents();
        jTFUser.setEnabled(true);
        jTFPass.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFUser = new javax.swing.JTextField();
        jTFPass = new javax.swing.JTextField();
        jBIniciarSesion = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jB1 = new javax.swing.JButton();
        jB2 = new javax.swing.JButton();
        jB3 = new javax.swing.JButton();
        jB4 = new javax.swing.JButton();
        jB5 = new javax.swing.JButton();
        jB6 = new javax.swing.JButton();
        jB7 = new javax.swing.JButton();
        jB8 = new javax.swing.JButton();
        jB9 = new javax.swing.JButton();
        jB0 = new javax.swing.JButton();
        jBq = new javax.swing.JButton();
        jBw = new javax.swing.JButton();
        jBe = new javax.swing.JButton();
        jBr = new javax.swing.JButton();
        jBt = new javax.swing.JButton();
        jBy = new javax.swing.JButton();
        jBu = new javax.swing.JButton();
        jBi = new javax.swing.JButton();
        jBo = new javax.swing.JButton();
        jBp = new javax.swing.JButton();
        jBa = new javax.swing.JButton();
        jBs = new javax.swing.JButton();
        jBd = new javax.swing.JButton();
        jBf = new javax.swing.JButton();
        jBg = new javax.swing.JButton();
        jBh = new javax.swing.JButton();
        jBj = new javax.swing.JButton();
        jBk = new javax.swing.JButton();
        jBl = new javax.swing.JButton();
        jBgn = new javax.swing.JButton();
        jBz = new javax.swing.JButton();
        jBx = new javax.swing.JButton();
        jBc = new javax.swing.JButton();
        jBv = new javax.swing.JButton();
        jBb = new javax.swing.JButton();
        jBn = new javax.swing.JButton();
        jBm = new javax.swing.JButton();
        jBguionbajo = new javax.swing.JButton();
        jBguion = new javax.swing.JButton();
        jBDelete = new javax.swing.JButton();
        jBSwap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Usuario:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Contraseña:");

        jTFUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTFPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jBIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBIniciarSesion.setText("Iniciar sesión");
        jBIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIniciarSesionActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(4, 10));

        jB1.setText("1");
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });
        jPanel1.add(jB1);

        jB2.setText("2");
        jB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2ActionPerformed(evt);
            }
        });
        jPanel1.add(jB2);

        jB3.setText("3");
        jB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3ActionPerformed(evt);
            }
        });
        jPanel1.add(jB3);

        jB4.setText("4");
        jB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB4ActionPerformed(evt);
            }
        });
        jPanel1.add(jB4);

        jB5.setText("5");
        jB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB5ActionPerformed(evt);
            }
        });
        jPanel1.add(jB5);

        jB6.setText("6");
        jB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB6ActionPerformed(evt);
            }
        });
        jPanel1.add(jB6);

        jB7.setText("7");
        jB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB7ActionPerformed(evt);
            }
        });
        jPanel1.add(jB7);

        jB8.setText("8");
        jB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB8ActionPerformed(evt);
            }
        });
        jPanel1.add(jB8);

        jB9.setText("9");
        jB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB9ActionPerformed(evt);
            }
        });
        jPanel1.add(jB9);

        jB0.setText("0");
        jB0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB0ActionPerformed(evt);
            }
        });
        jPanel1.add(jB0);

        jBq.setText("q");
        jBq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBqActionPerformed(evt);
            }
        });
        jPanel1.add(jBq);

        jBw.setText("w");
        jBw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBwActionPerformed(evt);
            }
        });
        jPanel1.add(jBw);

        jBe.setText("e");
        jBe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeActionPerformed(evt);
            }
        });
        jPanel1.add(jBe);

        jBr.setText("r");
        jBr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrActionPerformed(evt);
            }
        });
        jPanel1.add(jBr);

        jBt.setText("t");
        jBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtActionPerformed(evt);
            }
        });
        jPanel1.add(jBt);

        jBy.setText("y");
        jBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jByActionPerformed(evt);
            }
        });
        jPanel1.add(jBy);

        jBu.setText("u");
        jBu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuActionPerformed(evt);
            }
        });
        jPanel1.add(jBu);

        jBi.setText("i");
        jBi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBiActionPerformed(evt);
            }
        });
        jPanel1.add(jBi);

        jBo.setText("o");
        jBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoActionPerformed(evt);
            }
        });
        jPanel1.add(jBo);

        jBp.setText("p");
        jBp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpActionPerformed(evt);
            }
        });
        jPanel1.add(jBp);

        jBa.setText("a");
        jBa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaActionPerformed(evt);
            }
        });
        jPanel1.add(jBa);

        jBs.setText("s");
        jBs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsActionPerformed(evt);
            }
        });
        jPanel1.add(jBs);

        jBd.setText("d");
        jBd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdActionPerformed(evt);
            }
        });
        jPanel1.add(jBd);

        jBf.setText("f");
        jBf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBfActionPerformed(evt);
            }
        });
        jPanel1.add(jBf);

        jBg.setText("g");
        jBg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBgActionPerformed(evt);
            }
        });
        jPanel1.add(jBg);

        jBh.setText("h");
        jBh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBhActionPerformed(evt);
            }
        });
        jPanel1.add(jBh);

        jBj.setText("j");
        jBj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBjActionPerformed(evt);
            }
        });
        jPanel1.add(jBj);

        jBk.setText("k");
        jBk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBkActionPerformed(evt);
            }
        });
        jPanel1.add(jBk);

        jBl.setText("l");
        jBl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlActionPerformed(evt);
            }
        });
        jPanel1.add(jBl);

        jBgn.setText("ñ");
        jBgn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBgnActionPerformed(evt);
            }
        });
        jPanel1.add(jBgn);

        jBz.setText("z");
        jBz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBzActionPerformed(evt);
            }
        });
        jPanel1.add(jBz);

        jBx.setText("x");
        jBx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBxActionPerformed(evt);
            }
        });
        jPanel1.add(jBx);

        jBc.setText("c");
        jBc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcActionPerformed(evt);
            }
        });
        jPanel1.add(jBc);

        jBv.setText("v");
        jBv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvActionPerformed(evt);
            }
        });
        jPanel1.add(jBv);

        jBb.setText("b");
        jBb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbActionPerformed(evt);
            }
        });
        jPanel1.add(jBb);

        jBn.setText("n");
        jBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnActionPerformed(evt);
            }
        });
        jPanel1.add(jBn);

        jBm.setText("m");
        jBm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmActionPerformed(evt);
            }
        });
        jPanel1.add(jBm);

        jBguionbajo.setText("_");
        jBguionbajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguionbajoActionPerformed(evt);
            }
        });
        jPanel1.add(jBguionbajo);

        jBguion.setText("-");
        jBguion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguionActionPerformed(evt);
            }
        });
        jPanel1.add(jBguion);

        jBDelete.setText("DEL");
        jBDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jBDelete);

        jBSwap.setText("SWAP");
        jBSwap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSwapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTFUser, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jBSwap, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFPass, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(15, 15, 15))))
            .addGroup(layout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(jBIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFUser, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTFPass, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBSwap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIniciarSesionActionPerformed
        String nombreUsuario = this.jTFUser.getText();
        String contraseña = this.jTFPass.getText();
        // Comprueba que ambos campos estan rellenos
        if (nombreUsuario.length() > 0 && contraseña.length() > 0) {
            // Asignamos al objeto usuario el objeto usuario que obtenemos con buscarUsuario()
            usuario = conexionUsuario.buscarUsuario(nombreUsuario, contraseña);
            // si usuario es nulo es porque ha fallado el buscar
            if (usuario != null) {
                if (usuario.getRol().equals("admin") || usuario.getRol().equals("vendedor")) {
                    // si el rol es admin o vendedor entra y muestra la siguiente interfaz, escondiendo esta
                    TPVGUI tpv = new TPVGUI(usuario);
                    tpv.setVisible(true);
                    this.setVisible(false);
                } else {
                    // si el rol no es ninguno de esos dos, mostramos:
                    JOptionPane.showMessageDialog(null, "Ese rol no es válido.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                // si el usuario es nulo es porque no se ha encontrado un usuario con esas credenciales en nuestra BD
                JOptionPane.showMessageDialog(null, "El usuario no está registrado como tal en la BD.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {

            JOptionPane.showMessageDialog(null, "Los campos usuario y contraseña no pueden estar vacíos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBIniciarSesionActionPerformed

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed
        dondeEscribir('1');
    }//GEN-LAST:event_jB1ActionPerformed

    private void jB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB2ActionPerformed
        dondeEscribir('2');
    }//GEN-LAST:event_jB2ActionPerformed

    private void jB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB3ActionPerformed
        dondeEscribir('3');
    }//GEN-LAST:event_jB3ActionPerformed

    private void jB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB4ActionPerformed
        dondeEscribir('4');
    }//GEN-LAST:event_jB4ActionPerformed

    private void jB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB5ActionPerformed
        dondeEscribir('5');
    }//GEN-LAST:event_jB5ActionPerformed

    private void jB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB6ActionPerformed
        dondeEscribir('6');
    }//GEN-LAST:event_jB6ActionPerformed

    private void jB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB7ActionPerformed
        dondeEscribir('7');
    }//GEN-LAST:event_jB7ActionPerformed

    private void jB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB8ActionPerformed
        dondeEscribir('8');
    }//GEN-LAST:event_jB8ActionPerformed

    private void jB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB9ActionPerformed
        dondeEscribir('9');
    }//GEN-LAST:event_jB9ActionPerformed

    private void jB0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB0ActionPerformed
        dondeEscribir('0');
    }//GEN-LAST:event_jB0ActionPerformed

    private void jBqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBqActionPerformed
        dondeEscribir('q');
    }//GEN-LAST:event_jBqActionPerformed

    private void jBwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBwActionPerformed
        dondeEscribir('w');
    }//GEN-LAST:event_jBwActionPerformed

    private void jBeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeActionPerformed
        dondeEscribir('e');
    }//GEN-LAST:event_jBeActionPerformed

    private void jBrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrActionPerformed
        dondeEscribir('r');
    }//GEN-LAST:event_jBrActionPerformed

    private void jBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtActionPerformed
        dondeEscribir('t');
    }//GEN-LAST:event_jBtActionPerformed

    private void jByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jByActionPerformed
        dondeEscribir('y');
    }//GEN-LAST:event_jByActionPerformed

    private void jBuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuActionPerformed
        dondeEscribir('u');
    }//GEN-LAST:event_jBuActionPerformed

    private void jBiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBiActionPerformed
        dondeEscribir('i');
    }//GEN-LAST:event_jBiActionPerformed

    private void jBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoActionPerformed
        dondeEscribir('o');
    }//GEN-LAST:event_jBoActionPerformed

    private void jBpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpActionPerformed
        dondeEscribir('p');
    }//GEN-LAST:event_jBpActionPerformed

    private void jBaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaActionPerformed
        dondeEscribir('a');
    }//GEN-LAST:event_jBaActionPerformed

    private void jBsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsActionPerformed
        dondeEscribir('s');
    }//GEN-LAST:event_jBsActionPerformed

    private void jBdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdActionPerformed
        dondeEscribir('d');
    }//GEN-LAST:event_jBdActionPerformed

    private void jBfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBfActionPerformed
        dondeEscribir('f');
    }//GEN-LAST:event_jBfActionPerformed

    private void jBgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBgActionPerformed
        dondeEscribir('g');
    }//GEN-LAST:event_jBgActionPerformed

    private void jBhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBhActionPerformed
        dondeEscribir('h');
    }//GEN-LAST:event_jBhActionPerformed

    private void jBjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBjActionPerformed
        dondeEscribir('j');
    }//GEN-LAST:event_jBjActionPerformed

    private void jBkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBkActionPerformed
        dondeEscribir('k');
    }//GEN-LAST:event_jBkActionPerformed

    private void jBlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlActionPerformed
        dondeEscribir('l');
    }//GEN-LAST:event_jBlActionPerformed

    private void jBgnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBgnActionPerformed
        dondeEscribir('ñ');
    }//GEN-LAST:event_jBgnActionPerformed

    private void jBzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBzActionPerformed
        dondeEscribir('z');
    }//GEN-LAST:event_jBzActionPerformed

    private void jBxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBxActionPerformed
        dondeEscribir('x');
    }//GEN-LAST:event_jBxActionPerformed

    private void jBcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcActionPerformed
        dondeEscribir('c');
    }//GEN-LAST:event_jBcActionPerformed

    private void jBvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvActionPerformed
        dondeEscribir('v');
    }//GEN-LAST:event_jBvActionPerformed

    private void jBbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbActionPerformed
        dondeEscribir('b');
    }//GEN-LAST:event_jBbActionPerformed

    private void jBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnActionPerformed
        dondeEscribir('n');
    }//GEN-LAST:event_jBnActionPerformed

    private void jBmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmActionPerformed
        dondeEscribir('m');
    }//GEN-LAST:event_jBmActionPerformed

    private void jBguionbajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguionbajoActionPerformed
        dondeEscribir('_');
    }//GEN-LAST:event_jBguionbajoActionPerformed

    private void jBguionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguionActionPerformed
        dondeEscribir('-');
    }//GEN-LAST:event_jBguionActionPerformed

    private void jBSwapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSwapActionPerformed
        swapeoTexto();
    }//GEN-LAST:event_jBSwapActionPerformed

    private void jBDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeleteActionPerformed
        borrarUltimo();
    }//GEN-LAST:event_jBDeleteActionPerformed

    /**
     * Método para cambiar el valor del booleano escribeEnUsuario y según el
     * mismo, habilitar y deshabilitar los TextFields
     *
     * @return
     */
    public boolean swapeoTexto() {
        escribeEnUsuario = !escribeEnUsuario;
        if (escribeEnUsuario == true) {
            this.jTFUser.setEnabled(true);
            this.jTFPass.setEnabled(false);
        } else {
            this.jTFUser.setEnabled(false);
            this.jTFPass.setEnabled(true);
        }
        return escribeEnUsuario;
    }

    /**
     * Método con el que introducimos un caracter más dentro de la cadena,
     * dependiendo del selector
     *
     * @param c
     */
    public void dondeEscribir(char c) {
        if (escribeEnUsuario == true) {
            cadenaUser = cadenaUser + c;
            this.jTFUser.setText(cadenaUser);
        } else {
            cadenaPass = cadenaPass + c;
            this.jTFPass.setText(cadenaPass);
        }
    }

    /**
     * Método para borrar el último caracter de la cadena deseada y devolverla.
     * Checkea si hay caracteres que borrar, pudiendo mostrar salidas de error
     * al usuario. Actualiza el campo de usuario y password según se borra.
     *
     * @return
     */
    public String borrarUltimo() {
        // Usuario o contraseña
        if (escribeEnUsuario == true) {
            if (cadenaUser.length() > 0) {
                // Con esto borro el ultimo caracter de la cadena y la devuelvo
                this.cadenaUser = cadenaUser.substring(0, cadenaUser.length() - 1);
                // Comunico los cambios al TextField para que se muestre por pantalla
                this.jTFUser.setText(cadenaUser);
            } else {
                // Si el usuario trata de borrar caracteres de una cadena vacía
                JOptionPane.showMessageDialog(null, "El campo de username está vacío, no hay nada que borrar.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            // Devuelvo cadena
            return cadenaUser;
        } else {
            if (cadenaPass.length() > 0) {
                this.cadenaPass = cadenaPass.substring(0, cadenaPass.length() - 1);
                this.jTFPass.setText(cadenaPass);
            } else {
                JOptionPane.showMessageDialog(null, "El campo de password está vacío, no hay nada que borrar.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            return cadenaPass;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB0;
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB2;
    private javax.swing.JButton jB3;
    private javax.swing.JButton jB4;
    private javax.swing.JButton jB5;
    private javax.swing.JButton jB6;
    private javax.swing.JButton jB7;
    private javax.swing.JButton jB8;
    private javax.swing.JButton jB9;
    private javax.swing.JButton jBDelete;
    private javax.swing.JButton jBIniciarSesion;
    private javax.swing.JButton jBSwap;
    private javax.swing.JButton jBa;
    private javax.swing.JButton jBb;
    private javax.swing.JButton jBc;
    private javax.swing.JButton jBd;
    private javax.swing.JButton jBe;
    private javax.swing.JButton jBf;
    private javax.swing.JButton jBg;
    private javax.swing.JButton jBgn;
    private javax.swing.JButton jBguion;
    private javax.swing.JButton jBguionbajo;
    private javax.swing.JButton jBh;
    private javax.swing.JButton jBi;
    private javax.swing.JButton jBj;
    private javax.swing.JButton jBk;
    private javax.swing.JButton jBl;
    private javax.swing.JButton jBm;
    private javax.swing.JButton jBn;
    private javax.swing.JButton jBo;
    private javax.swing.JButton jBp;
    private javax.swing.JButton jBq;
    private javax.swing.JButton jBr;
    private javax.swing.JButton jBs;
    private javax.swing.JButton jBt;
    private javax.swing.JButton jBu;
    private javax.swing.JButton jBv;
    private javax.swing.JButton jBw;
    private javax.swing.JButton jBx;
    private javax.swing.JButton jBy;
    private javax.swing.JButton jBz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFPass;
    private javax.swing.JTextField jTFUser;
    // End of variables declaration//GEN-END:variables
}
